excluded:
  - SQLite.swift
  - Templates
  - Pods

whitelist_rules:
  - attributes
  - class_delegate_protocol
  - closing_brace
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - colon
  - comma
  - compiler_protocol_init
  - control_statement
  - custom_rules
  - dynamic_inline
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_init
  - first_where
  - generic_type_name
  - implicit_getter
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - mark
  - nimble_operator
  - opening_brace
  - operator_whitespace
  - overridden_super_call
  - private_unit_test
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_void_return
  - return_arrow_whitespace
  - shorthand_operator
  - statement_position
  - syntactic_sugar
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_name
  - unused_closure_parameter
  - unused_optional_binding
  - valid_docs
  - valid_ibinspectable
  - vertical_parameter_alignment
  - void_return
  - weak_delegate
