update_fastlane
fastlane_version "2.28.5"
default_platform :tvos

platform :tvos do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    cocoapods
  end

  desc "Builds and runs all the tests"
  lane :test do
    scan(scheme: "MapExplorer-tvOS", skip_slack: !is_ci, slack_only_on_failure: true)
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end
