use_frameworks!
project 'MapExplorer-macOS.xcodeproj'
platform :osx, '10.13'

target 'MapExplorer-macOS' do
    pod 'MONode', :git => 'git@github.com:SlantDesign/mo.git'
    pod 'Alamofire', '~> 4.5'

end
